#  SEMgraph library
#  Copyright (C) 2019-2021 Fernando Palluzzi; Mario Grassi
#  e-mail: <fernando.palluzzi@gmail.com>
#  University of Pavia, Department of Brain and Behavioral Sciences
#  Via Bassi 21, 27100 Pavia, Italy

#  SEMgraph is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  SEMgraph is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

# -------------------------------------------------------------------- #


#' @title Reactome interactome
#'
#' @description Interactome generated by merging Reactome pathways 
#' extracted using the \code{graphite} R package (update: April, 2020).
#' @name reactome
#' @usage reactome
#' @docType data
#' @format
#' "reactome" is an igraph network object of 9762 nodes and 416128 edges 
#' corresponding to the union of 1641 Reactome pathways.
#' @source \url{https://reactome.org}
#' @references
#' 
#' Jassal B, Matthews L, Viteri G, Gong C, Lorente P, Fabregat A, 
#' Sidiropoulos K, Cook J, Gillespie M, Haw R, Loney F, May B, Milacic M, 
#' Rothfels K, Sevilla C, Shamovsky V, Shorser S, Varusai T, Weiser J, 
#' Wu G, Stein L, Hermjakob H, D'Eustachio P. 
#' The reactome pathway knowledgebase. 
#' Nucleic Acids Res. 2020 Jan 8;48(D1):D498-D503. 
#' doi: 10.1093/nar/gkz1031. PubMed PMID: 31691815.
#' 
#' Martini P, Sales G, Massa MS, Chiogna M, Romualdi C. Along signal paths: 
#' anempirical gene set approach exploiting pathway topology. 
#' Nucleic Acids Res. 41(1):e19.
#' https://doi.org/10.1093/nar/gks866.
#' 
#' @examples
#' 
#' summary(reactome)
#' 
#' # Reactome degrees of freedom
#' vcount(reactome)*(vcount(reactome) - 1)/2 - ecount(reactome)
#' 
#' # Reactome average shortest path length
#' mean_distance(reactome)
NULL
